# Acceso a casillas, filas y columnas

Crea un programa llamado CasasRurales.py que cargue en un data frame los datos del CSV que se te proporcionará.

In [1]:
import pandas as pd

df = pd.read_csv("casas_rurales.csv", sep=";")
df

,id,localidad,codigo_postal,nombre,modalidad,categoria,tipo_via,via,numero,telefono,email,web,ubicacion
0,1,Aín,12222,MOLI DEL DUC,R,2,C,DE L'AIGUA,11,964629064.0,info@molidelduc.es,http://www.molidelduc.es,"39.90966000000003, -0.339261590999967"
1,7,Albocàsser,12140,CASA SALES,R,2,C,TRAS LA IGLESIA,22,964428432.0,info@turistrat.es,www.turistrat.es,"40.38227065700005, 0.019430000000056003"
2,17,Alcudia de Veo,12222,ALMAZARA VEO,R,1,C,ENMEDIO,32,615538003.0,info@casaruralalmazaradeveo.com,NaN,"39.91857259000005, -0.34003084999994804"
3,18,Alcudia de Veo,12222,CASA BENITANDUS-44,R,2,C,Benitandus,44,655936106.0,jfranchcabedo@gmail.com / rose69am@gmail.com,http://benitandus.com,"39.91857259000005, -0.34003084999994804"
4,21,Algimia de Almonacid,12414,LA CASITA DE LAS ESTRELLAS,R,2,C,Carcabo,18,964139400.0,info@lacasitadelasestrellas.com,lacasitadelasestrellas.com,"39.909575000000075, -0.43718342499994306"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
418,407,Vistabella del Maestrat,12135,CASA CLERIG,R,2,C,MAYOR,7,615688044.0,NaN,NaN,"40.29920000000004, -0.313153613999929"
419,408,Vistabella del Maestrat,12135,CASA RURAL CAL PUENTO,R,2,CM,ARRABAL DE SAN JUAN,11,964389025.0,NaN,NaN,"40.29920000000004, -0.313153613999929"
420,413,Viver,12460,LA CASA BONITA,R,2,AV,DIPUTACION,3,964141056.0,sandrasanju@hotmail.com,NaN,"39.930105000000026, -0.6242169679999271"
421,419,Xert,12360,CASA RURAL RUSTIC SUITES,R,3,PD,INDEPENDENCIA,47,687472516.0,odette@casaconjacuzzi.com,http://www.casaconjacuzzi.com,"40.54171000000008, 0.140162690000067"
422,422,Xodos/Chodos,12134,LA PALLISSA,R,2,C,Ferreria,9,964428432.0,info@turistrat.es,www.turistrat.es,"40.23246000000006, -0.29319931699996005"

Queremos quedarnos solo con las 4 primeras columnas (id, localidad, codigo_postal y nombre), transformando el id y el codigo_postal a enteros de 32 bits.

In [2]:
#df_lite = df.loc[:, ["id", "localidad", "codigo_postal", "nombre"]]
df_lite = df.iloc[:, 0:4]
df_lite

      id                localidad  codigo_postal                      nombre
0      1                      Aín          12222                MOLI DEL DUC
1      7               Albocàsser          12140                  CASA SALES
2     17           Alcudia de Veo          12222                ALMAZARA VEO
3     18           Alcudia de Veo          12222          CASA BENITANDUS-44
4     21     Algimia de Almonacid          12414  LA CASITA DE LAS ESTRELLAS
..   ...                      ...            ...                         ...
418  407  Vistabella del Maestrat          12135                 CASA CLERIG
419  408  Vistabella del Maestrat          12135       CASA RURAL CAL PUENTO
420  413                    Viver          12460              LA CASA BONITA
421  419                     Xert          12360    CASA RURAL RUSTIC SUITES
422  422             Xodos/Chodos          12134                 LA PALLISSA

[423 rows x 4 columns]

In [3]:
print(df_lite.dtypes)

id                int64
localidad        object
codigo_postal     int64
nombre           object
dtype: object

In [4]:
df_lite = df_lite.astype({"id": "int32", "codigo_postal": "int32"})
print(df_lite.dtypes)

id                int32
localidad        object
codigo_postal     int32
nombre           object
dtype: object

Guarda el resultado en un archivo llamado casas_rurales_resumen.csv

In [8]:
df_lite.to_csv("casas_rurales_resumen.csv", index=False, sep=';')